name: Update README

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch content
        run: |
          curl -s https://raw.githubusercontent.com/aiboboxx/clashfree/refs/heads/main/README.md | head -n 1 > temp.txt

      - name: Extract date and time
        run: |
          TIME=$(grep -oP '\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}' temp.txt)
          echo "$TIME" > README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md" || echo "No changes to commit"
          git push
