name: Update README.md

on:
  workflow_dispatch: 
  schedule: 
    - cron: '0 * * * *'

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
    - name: 檢出代碼庫
      uses: actions/checkout@v2

    - name: 設置 Git
      run: |
        git config --local user.email "chuangyustar@gmail.com"
        git config --local user.name "zxsman"

    - name: 獲取上游更改
      run: |
        git remote add upstream https://github.com/aiboboxx/clashfree.git
        git fetch upstream
        git checkout main  
        git pull --no-rebase upstream main  # 使用合併策略

    - name: 顯示修改前的 README.md
      run: cat README.md

    - name: 修改 README.md
      run: |
        first_line=$(head -n 1 README.md)
        
        if [[ $first_line =~ ([0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}) ]]; then
          echo "${BASH_REMATCH[1]}" > README.md
        else
          echo "未找到日期" > README.md
        fi

    - name: 顯示修改後的 README.md
      run: cat README.md

    - name: 提交並推送更改
      run: |
        git add README.md
        git commit -m "更新日期" || echo "沒有更改需要提交"
        
        # 推送更改到倉庫
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
