name: Update Clashtc File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --local user.email "chuangyustar@gmail.com"
        git config --local user.name "zxsman"

    - name: Fetch upstream changes
      run: |
        git remote add upstream https://github.com/aiboboxx/clashfree.git
        git fetch upstream
        git checkout main  
        git merge upstream/main || echo "Merge conflicts detected, resolving..."

    - name: Download clash.yml
      run: |
        curl -o clash.yml https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml

    - name: Replace 🇨🇳 with 🇹🇼
      run: |
        sed -i 's/🇨🇳/🇹🇼/g' clash.yml

    - name: Install OpenCC
      run: |
        sudo apt-get update
        sudo apt-get install -y opencc

    - name: Convert Simplified Chinese to Traditional Chinese
      run: |
        opencc -i clash.yml -o clash_traditional.yml -c s2t.json
        mv clash_traditional.yml clashtc.yml

    - name: Commit and push changes
      run: |
        git add clashtc.yml
        git commit -m "Update clashtc.yml" || echo "No changes to commit"
        
        # Push changes to the repository
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
